### PR TITLE
Only handle GET and HEAD requests, 405 all others.

### LINKED ISSUE #8: Chunkers not ending when HTTP HEAD requests are made
I've recently noticed an issue where `mjpeg-proxy` would no longer realize that connections have ended.
I'm using it behind an NGINX reverse proxy.

`sudo bandwhich -i eth0` reveals:
image
(Only small poll connections, nothing related to mjpeg-proxy, is hitting NGINX)
The log of my systemd unit for mjpeg-proxy reveals the following:
image
This stays true even when I stop NGINX entirely - mjpeg-proxy will still think those connections are open, even though nothing is connected to it anymore.

### PR DESCRIPTION
**Pull request by kescherCode**
Fixes #8.

Signed-off-by: Jeremy Kescher <jeremy@kescher.at>

### CODE REVIEW

**Comment by kescherCode** [comment]
In the future, we could try switching to `http.HandleFunc()` entirely (which allows setting allowed request methods directly), but that requires quite some restructuring of the code.

**Comment by vvidic** [comment]
I'm not sure this completely handles the case of the HTTP client going away. Can you check if the change I just sent solves the issue you reported?

**Comment by kescherCode** [comment]
This code is already deployed, and I tested it with connection interruptions, etc.
Your change is a tad bit cleaner, yes (I will test it soon). However,
I guess only accepting GET and HEAD is still a good idea, as well as separating these two methods entirely (to avoid unneeded memory allocations for HEAD). Semantically, it makes no sense to reply to an OPTIONS, PUT or POST request with an MJPEG stream.

**Comment by vvidic** [comment]
Sure, HTTP handling is not 100% correct but I would prefer to keep things simple unless necessary. Also if HEAD is used for monitoring it should do as much work as GET, otherwise it might report success when the stream is in fact broken.

**Comment by kescherCode** [comment]
Hm, I suppose you are right on that. I will conduct my tests on the most recent shortly.

**Comment by kescherCode** [comment]
Yes, your changes fix the issue at hand much better. I will close this pull request and remove the branch, but I will submit a simpler fix for the allowed HTTP methods.

**Comment by kescherCode** [comment]
Follow-up: #10

**Pull request closed without merging**
