### PR TITLE
Quality of life pull request

### PR DESCRIPTION
**Pull request by kescherCode**
I applied gofmt, fixed some static analysis warnings, fixed up the Content-Type checking a bit, but **removed the checking for valid boundaries**, because some webcam streams (such as a lot of those by AXIS webcams) don't properly append the boundary name for each frame.
However, this shouldn't be an issue. This is a proxy, and, in my opinion, the proxy shouldn't be responsible for checking how valid the MJPEG stream is; it is just supposed to restream it.

### CODE REVIEW

**Comment by kescherCode** [comment]
Thanks a lot for merging the pull request! I might add more features in future pull requests, for instance, binding multiple streams to one process.

**Comment by vvidic** [comment]
On Sun, Jul 19, 2020 at 03:26:10AM -0700, Jeremy Kescher wrote:
> Thanks a lot for merging the pull request! I might add more features
> in future pull requests, for instance, binding multiple streams to one
> process.

No problem, I have updated the code some more now. Can you provide
some example of this Axis stream with invalid boundaries?

-- 
Valentin

**Comment by vvidic** [comment]
Just added support for multiple sources using a config file :)

**Comment by kescherCode** [comment]
@vvidic I can email you a URL which exhibits this behaviour, but for documentation purposes, here's what seems to happen:

Where the boundary marker usually should be for each frame, there is just a newline for all frames after the first one. This caused the proxy to forward just one image and then stop due to an invalid boundary (which is an empty string in the error message)

**Pull request merged**
