### PR TITLE
Allow serving from socket instead of Internet Protocol

### PR DESCRIPTION
**Pull request by kescherCode**
If bind is set to `unix:/path/to/socket`, we will serve to a Unix socket instead of binding to IP:Port. This is particularly useful when mjpeg-proxy is sitting behind a frontend proxy such as NGINX, Apache2, Caddy, etc., because there is more overhead to transmitting packets via the loopback interface (namely, IP headers that aren't needed) than there would be over a socket.

### CODE REVIEW

**Comment by vvidic** [comment]
I understand that Unix socket is more efficient, but I would prefer to keep things simple unless the optimization is really needed for some use case? Also there should only be one call to http.Serve for both cases.

**Comment by kescherCode** [comment]
The loopback interface has considerable overhead. I configure all applications possible to use sockets, which has the added advantage of simple ACL security as well, a useful thing on multi-user machines.

As for the `http.Serve`, only one of two is ever called. For sockets, we need to create our own socket listener and check the socket's path. When we don't use a socket, of course we can just call `http.ListenAndServe`. The two seperate calls are already the simple solution for incuding socket listening support for http, sadly. I hope that someday, Go receives support for http listening on sockets as many other http frameworks do (Express being a notable example), and this code can be simplified again.

On the topic of keeping things simple, it might make sense to split parts of this program into seperate Go files (but in the same package).

**Comment by vvidic** [comment]
On Thu, Nov 26, 2020 at 04:26:02PM -0800, Jeremy Kescher wrote:
> The loopback interface has considerable overhead. I configure all applications possible to use sockets, which has the added advantage of simple ACL security as well.
> 
> As for the `http.Serve`, only one of two is ever called. For sockets, we need to create our own socket listener and check the socket's path. When we don't use a socket, of course we can just call `http.ListenAndServe`. The two seperate calls are already the simple solution for the socket.
> 
> On the topic of keeping things simple, it might make sense to split parts of this program into seperate Go files (but in the same package).

https://stackoverflow.com/questions/14973942/tcp-loopback-connection-vs-unix-domain-socket-performance

Based on this Unix socket could be 10x faster, but unless you are doing
millions of frames per second this will still be like 1ns vs 10ns. Since
I only have one camera this doesn't matter much, perhaps you have more.
Anyways I will try to merge and cleanup afterwards...

-- 
Valentin

**Comment by kescherCode** [comment]
@vvidic This assumes that there is nothing else saturating the local loopback interface, as I've mentioned. If packets get stuck in loopback, this latency increases a lot. Actually, Cloudflare has run into this issue sometime around 2016, there should be a blog entry somewhere by them.

**Pull request merged**
